openapi: 3.0.0
x-runtime:
  httpserver:
    address: ":8082"
  logger:
    level: "INFO"
    output: "STDOUT"
  stats:
    output: "NULL"
  signals:
    installed:
      - "OS"
    os:
      signals:
        - 2 # SIGINT
        - 15 # SIGTERM
  connstate:
    reportinterval: "5s"
    hijackedcounter: "http.server.connstate.hijacked"
    closedcounter: "http.server.connstate.closed"
    idlegauge: "http.server.connstate.idle.gauge"
    idlecounter: "http.server.connstate.idle"
    activegauge: "http.server.connstate.active.gauge"
    activecounter: "http.server.connstate.active"
    newgauge: "http.server.connstate.new.gauge"
    newcounter: "http.server.connstate.new"
x-transportd:
  backends:
    - nexpose
    - queue
  nexpose:
    host: "${NEXPOSE_API_HOST}"
    pool:
      ttl: "15m"
      count: 1
  queue:
    host: "${HTTPPRODUCER_API_HOST}"
    pool:
      ttl: "15m"
      count: 1
info:
  version: 1.0.0
  title: "nexpose-vuln-hydrator"
  description: "Collection of external APIs used by Nexpose-Vuln-Hydrator service"
  contact:
    name: Security Development
    email: secdev-external@atlassian.com
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /api/3/solutions/{id}:
    get:
      description: Returns the details for a solution that can remediate one or more vulnerabilities.
      parameters:
        - name: id
          in: path
          description: The identifier of the solution.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Solution"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
      x-transportd:
        backend: nexpose
        enabled:
          - "accesslog"
          - "requestvalidation"
          - "responsevalidation"
          - "timeout"
          - "retry"
          - "basicauth"
        timeout:
          after: "${NEXPOSE_API_TIMEOUT}"
        retry:
          backoff: "50ms"
          limit: 3
          codes:
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
            - 506
            - 507
            - 508
            - 509
            - 510
            - 511
        basicauth:
          username: "${NEXPOSE_USERNAME}"
          password: "${NEXPOSE_PASSWORD}"
  /api/3/vulnerabilities/{id}:
    get:
      summary: Vulnerability
      description: Returns the details for a vulnerability.
      parameters:
        - name: id
          in: path
          description: The identifier of the vulnerability.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vulnerability"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
      x-transportd:
        backend: nexpose
        enabled:
          - "accesslog"
          - "requestvalidation"
          - "responsevalidation"
          - "timeout"
          - "retry"
          - "basicauth"
        timeout:
          after: "${NEXPOSE_API_TIMEOUT}"
        retry:
          backoff: "50ms"
          limit: 3
          codes:
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
            - 506
            - 507
            - 508
            - 509
            - 510
            - 511
        basicauth:
          username: "${NEXPOSE_USERNAME}"
          password: "${NEXPOSE_PASSWORD}"
  /api/3/vulnerabilities/{id}/solutions:
    get:
      tags:
        - Vulnerability
      summary: Vulnerability Solutions
      description:
        Returns all solutions (across all platforms) that may be used to
        remediate this vulnerability.
      parameters:
        - name: id
          in: path
          description: The identifier of the vulnerability.
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VulnSolution"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        503:
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
      x-transportd:
        backend: nexpose
        enabled:
          - "accesslog"
          - "requestvalidation"
          - "responsevalidation"
          - "timeout"
          - "retry"
          - "basicauth"
        timeout:
          after: "${NEXPOSE_API_TIMEOUT}"
        retry:
          backoff: "50ms"
          limit: 3
          codes:
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
            - 506
            - 507
            - 508
            - 509
            - 510
            - 511
        basicauth:
          username: "${NEXPOSE_USERNAME}"
          password: "${NEXPOSE_PASSWORD}"
  /api/3/assets/{id}/vulnerabilities:
    get:
      tags:
        - Vulnerability Result
      summary: Asset Vulnerabilities
      description:
        Retrieves all vulnerability findings on an asset. A finding may
        be `invulnerable` if all instances have exceptions applied.
      parameters:
        - name: id
          in: path
          description: The identifier of the asset.
          required: true
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          description: The index of the page (zero-based) to retrieve.
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          description: The number of records per page to retrieve.
          schema:
            type: integer
            format: int32
            default: 10
        - name: sort
          in: query
          description:
            "The criteria to sort the records by, in the format: `property[,ASC|DESC]`.
            The default sort order is ascending. Multiple sort criteria can be specified
            using multiple sort query parameters."
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AssetVulnerability"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
        503:
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
      x-transportd:
        backend: nexpose
        enabled:
          - "accesslog"
          - "requestvalidation"
          - "responsevalidation"
          - "timeout"
          - "retry"
          - "basicauth"
        timeout:
          after: "${NEXPOSE_API_TIMEOUT}"
        retry:
          backoff: "50ms"
          limit: 3
          codes:
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
            - 506
            - 507
            - 508
            - 509
            - 510
            - 511
        basicauth:
          username: "${NEXPOSE_USERNAME}"
          password: "${NEXPOSE_PASSWORD}"
  /publish:
    post:
      summary: "Produce a scanned asset with hydrated vulns to a queue"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                # an asset needs either a hostname OR an IP (or both)
                - $ref: "#/components/schemas/AssetVulnerabilityEventWithIP"
                - $ref: "#/components/schemas/AssetVulnerabilityEventWithHostname"
      responses:
        "200":
          description: "Success"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NexposeError"
      x-transportd:
        backend: queue
        enabled:
          - "accesslog"
          - "requestvalidation"
          - "timeout"
          - "retry"
        timeout:
          after: "5s"
        retry:
          backoff: "50ms"
          limit: 3
          codes:
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
            - 506
            - 507
            - 508
            - 509
            - 510
            - 511
components:
  schemas:
    Solution:
      type: object
      properties:
        id:
          type: string
          description: The identifier of the solution.
        steps:
          $ref: "#/components/schemas/Steps"
    Steps:
      type: object
      properties:
        text:
          type: string
          description: Textual representation of the content.
          example: Use `apt-get upgrade` to upgrade libexpat1 to the latest version.
    Vulnerability:
      type: object
      properties:
        cvss:
          $ref: "#/components/schemas/VulnerabilityCvss"
        description:
          $ref: "#/components/schemas/ContentDescription"
        id:
          type: string
          description: The identifier of the vulnerability.
        title:
          type: string
          description: The title (summary) of the vulnerability.
          example: "Microsoft CVE-2017-11804: Scripting Engine Memory Corruption Vulnerability"
    VulnerabilityCvss:
      type: object
      properties:
        v2:
          $ref: "#/components/schemas/VulnerabilityCvssV2"
    VulnerabilityCvssV2:
      type: object
      properties:
        score:
          type: number
          format: double
          example: 4.4
          description: "The CVSS score, which ranges from 0-10."
    ContentDescription:
      type: object
      properties:
        text:
          type: string
          example: >-
            <p>A remote code execution vulnerability exists in the way that the
            scripting engine handles objects in memory in Microsoft Edge. ...</p>
          description: Textual representation of the content.
      description: ""
    VulnSolution:
      type: object
      properties:
        resources:
          type: array
          description: The identifiers of the associated resources.
          items:
            type: string
      description: ""
    AssetVulnerability:
      type: object
      properties:
        page:
          $ref: "#/components/schemas/PageInfo"
        resources:
          type: array
          description: The page of resources returned.
          items:
            $ref: "#/components/schemas/VulnerabilityFinding"
    PageInfo:
      type: object
      properties:
        number:
          type: integer
          format: int64
          example: 6
          description: The index (zero-based) of the current page returned.
        size:
          type: integer
          format: int64
          example: 10
          description: The maximum size of the page returned.
        totalPages:
          type: integer
          format: int64
          example: 13
          description: The total number of pages available.
        totalResources:
          type: integer
          format: int64
          example: 123
          description: The total number of resources available across all pages.
      description: ""
    VulnerabilityFinding:
      type: object
      properties:
        id:
          type: string
          example: ssh-openssh-x11uselocalhost-x11-forwarding-session-hijack
          description: The identifier of the vulnerability.
        results:
          type: array
          description: >-
            The vulnerability check results for the finding. Multiple instances
            may be present if one or more checks fired, or a check has multiple
            independent results.
          items:
            $ref: "#/components/schemas/AssessmentResult"
        status:
          type: string
          example: vulnerable
          description: Status of a vulnerability, can be used to filter on.
      description: ""
    AssessmentResult:
      type: object
      properties:
        port:
          type: integer
          format: int32
          example: 22
          description: The port of the service the result was discovered on.
        protocol:
          type: string
          example: tcp
          description: The protocol of the service the result was discovered on.
        proof:
          type: string
          description: The proof explaining why the result was found vulnerable. The proof may container embedded HTML formatting markup.
    AssetVulnerabilityEventWithHostname:
      type: object
      description: "AssetVulnerabilityEventWithHostname contains the Asset info, and has vulnerability details"
      required:
        - scanTime
        - id
        - hostname
      properties:
        id:
          type: integer
          format: int64
          example: 282
          description: The identifier of the asset.
        hostname:
          type: string
          example: corporate-workstation-1102DC.acme.com
          description: The primary host name (local or FQDN) of the asset.
        scanTime:
          type: string
          format: date-time
          description: The time the asset was scanned in ISO8601 format.
        assetVulnerabilityDetails:
          type: array
          description: List of vulnerabilities found on the asset.
          items:
            $ref: "#/components/schemas/AssetVulnerabilityDetails"
    AssetVulnerabilityEventWithIP:
      type: object
      description: "AssetVulnerabilityEventWithIP contains the Asset info, and has vulnerability details"
      required:
        - id
        - ip
        - scanTime
      properties:
        id:
          type: integer
          format: int64
          example: 282
          description: The identifier of the asset.
        ip:
          type: string
          example: 182.34.74.202
          description: The primary IPv4 or IPv6 address of the asset.
        scanTime:
          type: string
          format: date-time
          description: The time the asset was scanned in ISO8601 format.
        assetVulnerabilityDetails:
          type: array
          description: List of vulnerabilities found on the asset.
          items:
            $ref: "#/components/schemas/AssetVulnerabilityDetails"
    AssetVulnerabilityDetails:
      type: object
      properties:
        id:
          type: string
          example: ssh-openssh-x11uselocalhost-x11-forwarding-session-hijack
          description: The identifier of the vulnerability.
        results:
          type: array
          description: >-
            The vulnerability check results for the finding. Multiple instances
            may be present if one or more checks fired, or a check has multiple
            independent results.
          items:
            $ref: "#/components/schemas/AssessmentResult"
        status:
          type: string
          example: vulnerable
          description: Status of a vulnerability, can be used to filter on.
        cvssV2Score:
          type: number
          format: double
          example: 4.4
          description: "The CVSS V2 score, which ranges from 0-10."
        cvssV2Severity:
          type: string
          example: Severe
          description: >-
            The severity of the vulnerability, one of: `"Moderate"`, `"Severe"`,
            `"Critical"`.
        description:
          type: string
          example: >-
            <p>A remote code execution vulnerability exists in the way that the
            scripting engine handles objects in memory in Microsoft Edge. ...</p>
          description: The description of the vulnerability.
        title:
          type: string
          example: >-
            Microsoft CVE-2017-11804: Scripting Engine Memory Corruption
            Vulnerability
          description: The title (summary) of the vulnerability.
        solutions:
          type: array
          items:
            type: string
          description: Solutions for remediation of the vulnerability.
    NexposeError:
      type: object
      properties:
        status:
          type: string
          description: The HTTP status code for the error (same as in the HTTP response).
        message:
          type: string
          description: The messages indicating the cause or reason for failure.
